views.py
import asyncio
import os

import aiohttp
from dotenv import load_dotenv

from flask import Blueprint, render_template, request, url_for, flash, redirect, session, jsonify

import psycopg2
from psycopg2 import sql

from db import conn_params

from google_auth_oauthlib.flow import Flow
from google.auth.transport import requests
from google.oauth2 import id_token

from functools import wraps  # Decorators

from forms import SignUpForm, LoginForm
from mail import mail_main

from flask_apscheduler import APScheduler
from apscheduler.schedulers.background import BackgroundScheduler


load_dotenv('.env')

views = Blueprint('views', __name__)

# Disabling HTTPs requirement for dev purposes
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

flow = Flow.from_client_secrets_file(
    os.getcwd() + "\static\client_secret_84706046961-bh1h1atvjaim09r3qh1ta1c2v3tefk92.apps.googleusercontent.com.json",
    scopes=['openid', 'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile'],
    redirect_uri='http://localhost:5000/callback'
)


running = False


# Email outreach
# Decorator for requiring login
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            return redirect(url_for('views.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function


# Running the mail script
scheduler = APScheduler()



def run_outreach(user_id):
    asyncio.run(mail_main(user_id))


@views.route('/')
def index():
    return render_template('index.html')


@views.route('/signup')
def signup():
    return render_template('signup.html')


@views.route('/signup-user', methods=['POST'])
def signup_user():
    errors = None
    error_message = None
    form = SignUpForm(request.form)

    if form.validate():
        with psycopg2.connect(**conn_params) as conn:
            with conn.cursor() as cur:
                check_query = sql.SQL('''
                    SELECT email
                    FROM users
                    WHERE email = %s;
                ''')
                cur.execute(check_query, (form.email,))
                row = cur.fetchone()
                if row:
                    error_message = "Email already registered..."
                else:
                    insert_query = sql.SQL('''
                        INSERT INTO users(email, password, firstname)
                        VALUES (%s, %s, %s);
                    ''')
                    cur.execute(insert_query, (form.email, form.confirm, form.name,))

                    flash("Successfully Registered")
                    return redirect(url_for('views.dashboard'))
    else:
        errors = form.errors

    print("Name: ", form.name)
    print("Email: ", form.email)
    print("Password: ", form.password)
    print("Confirm Password: ", form.confirm)
    print("Is validated: ", form.validate())
    print("Form errors: ", form.errors)

    return render_template('signup.html', form=form, errors=errors, error_message=error_message)


@views.route('/login')
def login():
    return render_template('login.html')


@views.route('/login/user', methods=['POST'])
def login_user():
    errors = None
    error_message = None
    form = LoginForm(request.form)

    if form.validate():
        with psycopg2.connect(**conn_params) as conn:
            with conn.cursor() as cur:
                user_query = sql.SQL("""
                    SELECT email FROM users
                    WHERE email = %s;
                """)
                cur.execute(user_query, (form.email,))
                row = cur.fetchone()
                if row:
                    redirect(url_for('views.dashboard'))
                error_message = "User doesn't exist"
    else:
        errors = form.errors

    print("[FORM ERROR]: ", errors)

    return render_template('login.html', errors=errors,
                           error_message=error_message)


@views.route('/login/google')
def login_google():
    authorisation_url, state = flow.authorization_url()
    print("[AUTH_URL]", authorisation_url)
    session['state'] = state

    print("[AUTH_URL]: ", authorisation_url)
    print("[STATE]: ", state)

    # return render_template('login.html')
    return redirect(authorisation_url)


@views.route('/callback')
def callback():
    try:
        flow.fetch_token(authorization_response=request.url)

        session['state'] = request.args['state']

        credentials = flow.credentials
        id_info = id_token.verify_oauth2_token(
            credentials.id_token, requests.Request(), credentials.client_id)

        print("[ID INFO]: ", id_info)
        session['google_id'] = id_info.get('sub')
        session['name'] = id_info.get('name')
        session['user_id'] = id_info.get('email')

        with psycopg2.connect(**conn_params) as conn:
            with conn.cursor() as cur:
                db_query = sql.SQL("""
                    SELECT email from users
                    WHERE email = %s;
                """)
                cur.execute(db_query, (id_info.get('email'),))
                row = cur.fetchone()
                if row:
                    return redirect(url_for('views.dashboard'))

                insert_script = sql.SQL("""
                    INSERT INTO users (email, password, first_name, google_id)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT DO NOTHING;
                """)
                cur.execute(insert_script, (id_info.get('email'), os.getenv('GOOGLE_PLACEHOLDER_PASSWORD'),
                                            id_info.get('name'), id_info.get('sub')), )

        return redirect(url_for('views.dashboard'))

    except Exception as e:
        print("[CALLBACK ERROR]: ", e)
        return "Error processing google login", 500


@views.route('/logout')
@login_required
def logout():
    return


@views.route('/logout/user')
@login_required
def logout_user():
    if session['user_id']:
        session.pop('user_id', None)

    if session['state']:
        session.pop('state', None)

    return redirect(url_for('views.index'))


@views.route('/dashboard')
@login_required
def dashboard():
    with psycopg2.connect(**conn_params) as conn:
        with conn.cursor() as cur:
            db_query = sql.SQL("""
                SELECT * FROM sent_mail
                WHERE author = %s;
            """)
            cur.execute(db_query, (session['user_id'], ))
            sent_mail = cur.fetchall()
            print("[DASHBOARD]: SENT MAIL, ", sent_mail)

    # TODO: Make the add email button functional, take their email and password store in DB and use that for the script when they decide the press play

    return render_template('dashboard.html', sent_mail=sent_mail)


@views.route('/email-pair', methods=['POST'])
@login_required
def email_pair():
    return


@views.route('/start', methods=['POST'])
@login_required
def start_outreach():
    print("[START OUTREACH]: ", session['user_id'])
    global running
    global task

    if not running:
        task = asyncio.create_task(run_outreach(session['user_id']))

        # TODO: create a little green blip showing running
        running = True
        return jsonify({'message': 'running'})
    else:
        # TODO: process already running
        return jsonify({'message': 'already running'})


@views.route('/stop', methods=['POST'])
@login_required
def stop_outreach():
    global running
    global task

    if running:
        task.cancel()
        # TODO: return the new blip with red showing not running

    else:
        return jsonify({'message': 'No process is currently running'})

    running = False


@views.route('/notis')
def get_notis():
    return render_template('notis.html')

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="/static/images/Bold Modern Minimalist Gradient Technology Business Logo.png">
    <title>{% block title %} {% endblock %}</title>

    <style>
        body {
            font-family: 'Poppins', sans-serif;
        }

        .fullscreen-center {
            min-height: 80vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .borderless {
            border-color: none !important;
        }

        .login-card {
            width: 100%;
            max-width: 400px;
            border: none;
            margin: 0 auto;
        }

        .btn-outline-google {
            border:  1px solid red;
            background-color: white;
            border-radius: 0.35em;
        }
    </style>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<!--suppress BuyFluidPluginNoteInspection -->
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <div>
                <img src="/static/images/Bold Modern Minimalist Gradient Technology Business Logo.png" style="width: 3rem;" alt="Logo">
                <a href="/dashboard" class="navbar-brand">Outreach</a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a href="/login" class="nav-link active" aria-current="page"></a>
                    </li>
                    <li class="nav-item">
                        <a href="/signup" class="nav-link active" aria-current="page"></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<style>
    table {
        font-size: 1.2rem;
    }

    @media (max-width: 500px) {
        table {
            font-size: 1rem;
        }
    }

    .table {
        margin-top: 1rem;
    }

    .phone-number {
        width: 150px;
        white-space: nowrap;
    }

    .table-wrapper {
        overflow-x:auto;
    }

    .email-pair {
        margin-top: 1rem;
    }

    th {
        font-weight: 600;
        white-space: nowrap;
        margin-left: 1rem;
    }
</style>
<main role="main">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center email-pair">
            <div class="container text-start">
                <button class="btn btn-primary" onclick="emailPair()">Add Email</button>
                <input  onkeyup="queryTable()" type="text" id="searchInput" class="form-control" placeholder="Search...">
            </div>
            <div class="text-end">
                <button class="btn btn-outline-secondary" onclick="startOutreach()">&#9654;</button>
                <button class="btn btn-outline-secondary" onclick="stopOutreach()">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pause" viewBox="0 0 16 16">
                        <path d="M6 3.5a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V4a.5.5 0 0 1 .5-.5m4 0a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V4a.5.5 0 0 1 .5-.5"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>


    <!-- Outreach data table -->
    <div class="container shadow">
        <div class="table-wrapper">
            <table class="table" id="myTable">
                <thead>
                <tr>
                    <th scope="col">Business Name</th>
                    <th scope="col">Website</th>
                    <th scope="col">Email</th>
                </tr>
                </thead>
                <tbody>
                {% for email in sent_mail %}
                    <tr>
                        <td>{{ email[2] }}</td>
                        <td>
                            <a href="{{ email[3] }}" target="_blank">{{ email[3] }}</a>
                        </td>
                        <td>
                            <a href="{{ email[0] }}" target="_blank">{{ email[0] }}</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-between align-items-center mt-3">
            <div id="rowCount"></div>
            <nav aria-label="Table Navigation">
                <ul class="pagination" id="pagination">
                    <li class="page-item"><a href="#" id="prevPage">Previous</a></li>
                    <li class="page-item"><a href="#" id="nextPage">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
</main>

<!-- Pair email overlay -->
<style>
    .login-card {
        width: 100%;
        max-width: 400px;
        border: none;
        margin: 0 auto;
    }

    #emailPair {
        position: fixed;
        top: 0;
        bottom: 0;
        height: 100%;
        width: 100%;
        display: none;
        z-index: 9999;
        background-color: rgba(0,0,0,0.5);
        align-items: center;
        justify-content: center;
        overflow: auto;
        margin: 0;
        padding: 0;
    }

    .close-larger {
        font-size: 2rem;
    }
</style>
<main role="main">
    <div id="emailPair">
        <div class="container text-center borderless">
            <div class="card p-3 login-card">
                <div class="card-title">
                    <div class="col text-end">
                        <button type="button" class="btn close close-larger" onclick="emailPair()" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="row">
                        <h3 class="card-title">Add Email</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ url_for('views.email_pair') }}" method="post">
                        <div class="row mb-4">
                            <label for="email" class="text-start col-sm-4 col-form-label col-form-label-sm">Email</label>
                            <br>
                            <input type="email" class="form-control form-control-sm" id="email" name="password" placeholder="johndoe@example.com" required>
                        </div>
                        <div class="row mb-4">
                            <label for="password" class="text-start col-sm-4 col-form-label col-form-label-sm">Password</label>
                            <br>
                            <input type="password" class="form-control form-control-sm" id="password" name="password" placeholder="chickenandeggs123" required>
                        </div>
                        <div class="row mb-3">
                            <label for="industries" class="text-start col-sm-4 col-form-label col-form-label-sm">Industries</label>
                            <br>
                            <input type="text" class="form-control form-control-sm" name="industries" id="industries" required>
                        </div>
                        <div class="row mb-3">
                            <input class="btn btn-outline-primary" type="submit" value="Submit">
                        </div>
                        <div class="row mb-4 tags"></div>
                        <small>Add up to 5 industries</small>
                        <div class="row mb-4">
                            <span><a href="https://www.youtube.com/watch?v=I9x0w8cjR_o&ab_channel=StudyGyaan" target="_blank">How to find your password?</a></span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

<style>
    .nav .nav-item a {
        font-size: 0.75rem;
    }
    ul li {
        margin-right: 1rem;
    }
</style>
<div class="b-example-divider"></div>
<div class="b-example-divider"></div>
<div class="b-example-divider"></div>
<div class="container">
    <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
        <div class="col mb-3">
            <a href="" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
                <svg class="bi me-2">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>
            <p class="text-body-secondary">© 2024</p>
        </div>
        <div class="col mb-3"></div> <!-- Space between columns -->
        <div class="col mb-3">
            <h5>About</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2">
                    <a href="#" class="nav-link p-0 text-body-secondary">How to find password?</a>
                </li>
                <li class="nav-item mb-2">
                    <a href="#" class="nav-link p-0 text-body-secondary">How to get telegram notifications?</a>
                </li>
            </ul>
        </div>
    </footer>
</div>

<script>
    let filteredRows = [];
    const rowsPerPage = 50;
    let currentPage = 1;
    const table = document.getElementById('myTable');
    const tbody = table.querySelector('tbody');
    const rows = Array.from(tbody.querySelectorAll('tr'));
    const totalRows = rows.length;

    const prevPageBtn = document.getElementById('prevPage');
    const nextPageBtn = document.getElementById('nextPage');
    const rowCountDisplay = document.getElementById('rowCount');

    function displayTable() {
        const startIndex = (currentPage - 1) * rowsPerPage;
        const endIndex = startIndex + rowsPerPage;
        const displayedRows = filteredRows.slice(startIndex, endIndex);

        tbody.innerHTML = '';
        displayedRows.forEach(row => tbody.appendChild(row));

        updatePaginationControls();
        updateRowCount();
    }

    function updatePaginationControls() {
        const totalPages = Math.ceil(filteredRows.length / rowsPerPage);
        prevPageBtn.classList.toggle('disabled', currentPage === 1);
        nextPageBtn.classList.toggle('disabled', currentPage === totalPages);
    }

    function updateRowCount() {
        const startIndex = (currentPage - 1) * rowsPerPage + 1;
        const endIndex = Math.min(currentPage * rowsPerPage, filteredRows.length);
        rowCountDisplay.textContent = `Showing ${startIndex} to ${endIndex} of ${filteredRows.length} entries`;
    }

    function queryTable() {
        const input = document.getElementById("searchInput");
        const filter = input.value.toUpperCase();

        filteredRows = rows.filter(row => {
            const td = row.getElementsByTagName("td")[0];
            if (td) {
                const txtValue = td.textContent || td.innerText;
                return txtValue.toUpperCase().indexOf(filter) > -1;
            }
            return false;
        });

        currentPage = 1;
        displayTable();
    }

    prevPageBtn.addEventListener('click', (e) => {
        e.preventDefault();
        if (currentPage > 1) {
            currentPage--;
            displayTable();
        }
    });

    nextPageBtn.addEventListener('click', (e) => {
        e.preventDefault();
        const totalPages = Math.ceil(filteredRows.length / rowsPerPage);
        if (currentPage < totalPages) {
            currentPage++;
            displayTable();
        }
    });

    // Initial setup
    filteredRows = rows;
    displayTable();

    // Add event listener to search input
    document.getElementById("searchInput").addEventListener('input', queryTable);
</script>
{% endblock %}

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block title %}Log In{% endblock %}

{% block content %}
<style>
    @media (min-width: 650px) {
        .login-card {
            width: 50%;
        }
    }
</style>
<main role="main" class="fullscreen-center">
    <div class="container text-center borderless">
        <div class="card p-3 login-card">
            <h3 class="card-title">Log In</h3>
            <div class="card-body">
                <form action="{{ url_for('views.login_user') }}" method="post">
                    <div class="row mb-3">
                        <label for="email" class="text-start col-sm-4 col-form-label col-form-label-sm">Email</label>
                        <br>
                        <input type="email" class="form-control form-control-sm" id="email" name="password" placeholder="johndoe@example.com">
                        {% if errors and errors.name %}
                            <span>{{ errors.name[0] }}</span>
                        {% endif %}
                    </div>
                    <div class="row mb-3">
                        <label for="password" class="text-start col-sm-6 col-form-label col-form-label-sm">Password</label>
                        <br>
                        <input type="password" class="form-control form-control-sm" id="password" name="password" placeholder="chickenandeggs123">
                    </div>
                    <div class="row mb-3">
                        <input class="btn btn-outline-primary" type="submit" value="Submit">
                    </div>
                    <div class="row mb-3">
                        <a href="{{ url_for('views.login_google') }}" class="btn btn-outline-google">
                            <img src="/static/images/Logo-google-icon-PNG.png" alt="Google Logo" style="width: 1.5rem; margin-right: 0.5rem;">
                            Sign in with Google
                        </a>
                    </div>
                    <div class="row mb-3">
                        {% if error_message %}
                        <span style="color: red;">{{ error_message }}</span>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/notis.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<style>
    h2 {
        font-size: 1rem;
    }

    .noti-card {
        justify-content: center;
        align-items: center;
    }

    .noti-btn {
        width: 100%;
    }

    .row {
        width: 100%;
    }
</style>
<main role="main" class="fullscreen-center">
    <div class="container text-center borderless">
        <div class="card p-3 login-card noti-card">
            <div class="card-title">
                <img src="/static/images/c7f3b7729e58e45def.png" alt="Logo" style="width: 25rem;">
            </div>
            <div class="card-body">
                <h2>To get your notifications <a href="https://t.me/https://t.me/nexifysolutions_bot">click here</a></h2>
            </div>
            <div class="row">
                <button type="button" class="btn btn-outline-primary  noti-btn">Next</button>
            </div>
        </div>
    </div>
</main>
{% endblock%}

templates/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}


{% block content %}
<style>
    .fullscreen-center {
        min-height: 80vh;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .borderless {
        border-color: none !important;
    }

    .login-card {
        width: 100%;
        max-width: 400px;
        border: none;
        margin: 0 auto;
    }

    .btn-outline-google {
        border:  1px solid red;
        background-color: white;
        border-radius: 0.35em;
    }

    .btn-outline-google:hover {
        background-color: red;
        color: white;
    }

    @media (min-width: 650px) {
        .login-card {
            width: 50%;
        }
    }
</style>
<main role="main" class="fullscreen-center">
    <div class="container text-center borderless">
        <div class="card p-3 login-card">
            <h3 class="card-title">Sign Up</h3>
            <div class="card-body">
                <form action="{{ url_for('views.signup_user') }}" method="post">
                    <div class="row mb-4">
                        <label for="name" class="text-start col-sm-4 col-form-label col-form-label-sm">Name</label>
                        <br>
                        <input type="text" class="form-control form-control-sm" id="name" name="name" placeholder="John">
                    </div>
                    <div class="row mb-4">
                        <label for="email" class="text-start col-sm-4 col-form-label col-form-label-sm">Email</label>
                        <br>
                        <input type="email" class="form-control form-control-sm" id="email" name="password" placeholder="johndoe@example.com" required>
                        {% if error and error.email %}
                        <span>{{ error.email[0] }}</span>
                        {% endif %}
                    </div>
                    <div class="row mb-4">
                        <label for="password" class="text-start col-sm-4 col-form-label col-form-label-sm">Password</label>
                        <br>
                        <input type="password" class="form-control form-control-sm" id="password" name="password" placeholder="*****" required>
                    </div>
                    <div class="row mb-4">
                        <label for="confirmPassword" class="text-start col-sm-6 col-form-label col-form-label-sm">Confirm Password</label>
                        <br>
                        <input type="password" class="form-control form-control-sm" id="confirmPassword" name="confirm_password" placeholder="*****" required>
                        {% if error and error.password %}
                        <span>{{ error.password[0] }}</span>
                        {% endif %}
                    </div>
                    <div class="row mb-3">
                        <input class="btn btn-outline-primary" type="submit" value="Submit">
                    </div>
                    <div class="row mb-3">
                        <a href="{{ url_for('views.login_google') }}" class="btn btn-outline-google">
                            <img src="/static/images/Logo-google-icon-PNG.png" alt="Google Logo" style="width: 1.5rem; margin-right: 0.5rem;">
                            Sign in with Google
                        </a>
                    </div>
<!--                    <div class="row mb-3 g-signin2" data-onsuccess="onSignIn">-->
<!--                        <button class="btn-outline-google">-->
<!--                            <img class="" src="/static/images/Logo-google-icon-PNG.png" alt="" style="width: 2rem;">-->
<!--                        </button>-->
<!--                    </div>-->
                    <div class="row mb-3">
                        {% if error_message %}
                        <span style="color: red">{{ error_message }}</span>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<!--<meta name="google-signin-client_id" content="84706046961-bh1h1atvjaim09r3qh1ta1c2v3tefk92.apps.googleusercontent.com">-->
<!--<script src="https://apis.google.com/js/platform.js" async defer></script>-->

<!--<script>-->
<!--    function onSignIn(googleUser) {-->
<!--      var profile = googleUser.getBasicProfile();-->
<!--      console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.-->
<!--      console.log('Name: ' + profile.getName());-->
<!--      console.log('Image URL: ' + profile.getImageUrl());-->
<!--      console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.-->
<!--    }-->
<!--</script>-->
{% endblock %}